# Built with Jekyll 3.2.0

# Setup
title:               Tom Collins and Company. 
tagline:             'Text editing and collaborative annotation' 
description:         'Tom Collins and Company aims to foster a deeper engagement with literary works through text editing and collaborative annotation.' 
url:                 'http://tomcollinsandcompany.github.io'
baseurl:             '/annotate'

# About/contact
author:
  name:              Roger Osborne
  url:               https://furphyarchive.wordpress.com/
  email:             tomcollinsandcompany@gmail.com

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


